lib/squareshop_web/router.ex
defmodule SquareshopWeb.Router do
  use SquareshopWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

	scope "/", SquareshopWeb do
		pipe_through :browser # Use the default browser stack
		get "/", PageController, :index
		get "/login", LoginController, :index
		get "/tos", TosController, :index
		get "/about", AboutController, :index
		get "/invoice", InvoiceController, :index
		resources "/shopping", ShoppingController
		resources "/products", ProductsController
		resources "/adminproducts", AdminProductsController
		resources "/adminuser", AdminUserController
    resources "/user", UserController
    get "/form", FormController, :index

    get "/sign-in", LoginController, :new
    post "/sign-in", LoginController, :create
    delete "/sign-out", LoginController, :delete
	end


  # Other scopes may use custom stacks.
  # scope "/api", SquareshopWeb do
  #   pipe_through :api
  # end
end

lib/squareshop/application.ex
defmodule Squareshop.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Squareshop.Repo, []),
      # Start the endpoint when the application starts
      supervisor(SquareshopWeb.Endpoint, []),
      # Start your own worker by calling: Squareshop.Worker.start_link(arg1, arg2, arg3)
      # worker(Squareshop.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Squareshop.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    SquareshopWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/squareshop/product/product.ex
defmodule Squareshop.Products do

	# Imports
	use Ecto.Schema
	import Ecto.Changeset
	import Ecto.Query, only: [from: 2]

	#Alias
	alias Squareshop.Repo
	alias Squareshop.Products
	alias Squareshop.Products.Product
	require Logger


	#search function

	def search(query, search_term) do
		wildcard_search = "%#{search_term}%"
	
		from product in query,
		where: ilike(product.name, ^wildcard_search),
		or_where: ilike(product.summary, ^wildcard_search)
	end


	#Add a product
	def create_product(productdata) do
		# Logger.debug("user_address = #{inspect(user_address)}")
		%Product{}
		|> Product.changeset(productdata)
		|> Repo.insert()
	end

	# Listing all the products
	def list_products() do
		Repo.all(Product)
	end

	def list_products(params) do
		search_term = get_in(params, ["query"])
	
		Product
		|> Products.search(search_term)
		|> Repo.all()
	end

	def get_product!(id) do
		 Repo.get!(Product, id)
	end

	# Helper function
	def change_product(%Product{} = products) do
		Product.changeset(products, %{})
	end

	def update_product(%Product{} = product, attrs) do

		Logger.debug("i ran")
		product
		|> Product.changeset(attrs)
		|> Repo.update()
	end


end

lib/squareshop/product/products.ex
defmodule Squareshop.Products.Product do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query

 	alias Squareshop.Repo
	alias Squareshop.Products
	alias Squareshop.Products.Product

	require Logger

  schema "products" do
    field :alternative_products, :integer
    field :base_price, :integer
    field :image, :map
    field :stock, :integer
    field :name, :string
    field :pnr, :string
    field :summary, :string
    field :supplier, :integer

    timestamps()
  end

  
  def list_products(params) do
    search_term = get_in(params, ["query"])

    Product
    |> Product.search(search_term)
    |> Repo.all()
  end

  def changeset(products, attrs) do
	  Logger.debug("number 2 ran")
    products
    |> cast(attrs, [:name, :pnr, :summary, :base_price, :stock, :supplier, :alternative_products])
    |> validate_required([:name, :pnr, :base_price, :stock, :supplier])
  end
end

lib/squareshop/repo.ex
defmodule Squareshop.Repo do
  use Ecto.Repo, otp_app: :squareshop

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/squareshop/sale/cart.ex
defmodule Squareshop.Sales.Cart do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
	  field :product_id, :integer
	  field :amount, :integer
  end


  def changeset(item, attrs) do

	  item
	  |> cast(attrs, [:product_id, :amount])
	  |> validate_required([:product_id, :amount])

  end
end

lib/squareshop/sale/orders.ex
defmodule Squareshop.Sales.Orders do
  use Ecto.Schema
  import Ecto.Changeset


  schema "orders" do
    field :Shipping_address, :string
    field :products, :map
    field :status, :integer
    field :user, :integer

    timestamps()
  end

  @doc false
  def changeset(orders, attrs) do
    orders
    |> cast(attrs, [:user, :products, :Shipping_address, :status])
    |> validate_required([:user, :products, :Shipping_address, :status])
  end
end

lib/squareshop/sale/sales.ex
defmodule Squareshop.Sales do
	#importing functions
		require Stripe
		import Ecto.Query
	#Setting up aliases
		alias Squareshop.Repo
		alias Squareshop.Sales
		alias Squareshop.Sales.Orders
		alias Squareshop.Identity
		alias Squareshop.Products
		alias Stripe
		alias Stripe.Charge


	def stripetest do
		 # obtained with Stripe.js
		Stripe.Charge.create(%{amount: 2000, currency: "nok", source: "tok_mastercard", description: "Charge for madison.anderson@example.com"})
	end

	def create_order(user_id, card) do
		user = Identity.get_user!(user_id)

		# for product <= user.shopping_cart do
		# Products.get_product!()
		# end



		Stripe.Charge.create(card)
	end

end

lib/squareshop_web/views/Shopping_view.ex
defmodule SquareshopWeb.ShoppingView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/about_view.ex
defmodule SquareshopWeb.AboutView do
   use SquareshopWeb, :view
end

lib/squareshop_web/views/error_view.ex
defmodule SquareshopWeb.ErrorView do
  use SquareshopWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/squareshop_web/views/form_view.ex
defmodule SquareshopWeb.FormView do
    use SquareshopWeb, :view
  end

lib/squareshop_web/views/homepage_view.ex
defmodule SquareshopWeb.HomepageView do
   use SquareshopWeb, :view
end

lib/squareshop_web/views/invoice_view.ex
defmodule SquareshopWeb.InvoiceView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/layout_view.ex
defmodule SquareshopWeb.LayoutView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/login_view.ex
defmodule SquareshopWeb.LoginView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/page_view.ex
defmodule SquareshopWeb.PageView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/products_view.ex
defmodule SquareshopWeb.ProductsView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/reg_user_view.ex
defmodule SquareshopWeb.RegUserView do
    use SquareshopWeb, :view
  end

lib/squareshop_web/views/register_view.ex
defmodule SquareshopWeb.Shared.RegisterView do
    use SquareshopWeb, :view
  end

lib/squareshop_web/views/tos_view.ex
defmodule SquareshopWeb.TosView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/user_view.ex
defmodule SquareshopWeb.UserView do
  use SquareshopWeb, :view
end

lib/squareshop_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Squareshop!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="sq-viewport">
  <div class="sq-1-3-grid">
    <nav class="sq-nav-area">
      <div role="navigation" class="sq-navbar-layout">
  		<div class="sq-navbar-nav  sq-secondary sq-text-right">
      <!--links -->
      <div class="sq-air-x-05">
      	<a href="#" class="sq-text-white sq-secondary sq-r-border sq-x-padding-05">Welcome to our store!</a>
      	<a href="#" class="sq-text-white sq-secondary sq-r-border sq-x-padding-05">Sign up for our newsletter</a>
      	<a href="#" class="sq-text-white sq-secondary sq-x-padding-05">Contact us</a>
      </div>
      <!--NAVBAR Part 2/3-->
  		</div>
  			<div class="sq-navbar-domain  sq-secondary" style="width:100%;display:flex;">
  				<a href="/" class="sq-text-white sq-secondary sq-margin-left">Home</a>
  				<div class="sq-flex-1"></div>

  				<!-- Searchbar -->
  				<div class="sq-flex-auto sq-form sq-text-center">
  					<%# <input type="text" placeholder="Search..." name="search" class="sq-nav-margin"> %>
            <%= form_for @conn, products_path(@conn, :index), [method: :get, class: "pull-right"], fn f -> %>
              <%= search_input f, :query, style: "width:50em;" %>
              <%= submit "Search" %>
            <% end %>
  				</div>
          <!-- Searchbar end-->

  				<!--ShoppingCart & SignIn buttons -->
  				<div class="sq-flex-1 sq-text-right">
  					<div class="sq-air-x-05 sq-nav-btn-group2 sq-flex-1">
        			<!-- UserButton -->
					<button class="sq-nav-btn2"><%= link "Register", to: user_path(@conn, :new), class: "sq-nounderline sq-white-text sq-margin-1" %></button>
            <button><%= link "Home", to: page_path(@conn, :index), class: "sq-nounderline sq-white-text" %></button>
            <%= if signed_in?(@conn) do %>
              <%= link "Sign out", to: login_path(@conn, :delete), method: :delete %>
              <% else %>
                <button><%= link "Sign in", to: login_path(@conn, :new), class: "sq-nounderline sq-white-text" %></button>
                <% end %>

        			<!-- ShoppingCartButton -->
        			<button><%= link "Cart", to: shopping_path(@conn, :index), class: "sq-nounderline sq-white-text"%></button>
    				</div>
  				</div>
  			</div>
  			<!--NAVBAR Part 3/3 -->
  			<div class="sq-navbar-links sq-secondary-highlight sq-text-center">
  				<div class="sq-nav-btn-group">
            <div class="sq-nav-dropdown">
              <button><a class="sq-nounderline sq-white-text" onclick="toggleDropdown()">Categories<span id="togglearrow"> &darr;</span></a></button>
              <div class="sq-nav-dropdown-content">
                <ul>
                  <li><a>Link 1</a></li>
                  <li><a>Link 2</a></li>
                  <li><a>Link 3</a></li>
                  <li><a>Link 4</a></li>
                  <li><a>Link 5</a></li>
                </ul>
              </div>
            </div>
            <button><a class="sq-nounderline sq-white-text" href="/products">Products</a></button>
  					<button><a class="sq-nounderline sq-white-text" href="/products">White Kopps</a></button>
  					<button><a class="sq-nounderline sq-white-text" href="/products">Big Black Kopps</a></button>
  					<button><a class="sq-nounderline sq-white-text" href="/products">Bestselgere</a></button>
  					<button><a class="sq-nounderline sq-white-text" href="/products">Kampanjer</a></button>
  					<button><a class="sq-nounderline sq-white-text" href="/user/1">Userpage</a></button>
  				</div>
  			</div>
  		</div>
    </nav>
    <main role="" class="sq-main">
    	<%= render @view_module, @view_template, assigns %>
    </main>
    <footer class="sq-secondary">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <div style="justify-content: space-around; margin-top: -0.4rem;" class="sq-secondary sq-flex sq-flex-row sq-justify-center"><div>
        <a href="#" onclick="toggleModal2()" class="sq-text-white sq-secondary">Social media</a>
      </div>
      <div>
        Phone: <a href="tel:0000" class="sq-text-white sq-secondary">#########</a>
      </div>
      <div>
        <a href="/about" class="sq-text-white sq-secondary">About</a>
      </div>
      <div>
        <a href="/support" class="sq-text-white sq-secondary">Support</a>
      </div>
      <div>
        <a href="/faq" class="sq-text-white sq-secondary">FAQ</a>
      </div>
      <div>
        <a href="mailto:nobody@online.no" class="sq-text-white sq-secondary">Mail</a>
      </div>
    </div>
  </footer>
  <div>
    <div onclick="toggleModal2()" id="socialMedia" class="sq-modal-social-media">
      <div onclick="toggleModal2()" class="sq-secondary sq-modal-content-social-media">
        <span class="sq-secondary sq-close-button" onclick="toggleModal2()">&times;</span>
        <!--box-->
          <div class="sq-social-media-icons">
            <div>
              <svg id="i-twitter" viewBox="0 0 64 64" width="8rem" height="8rem">
              <path stroke-width="0" fill="currentColor" d="M60 16 L54 17 L58 12 L51 14 C42 4 28 15 32 24 C16 24 8 12 8 12 C8 12 2 21 12 28 L6 26 C6 32 10 36 17 38 L10 38 C14 46 21 46 21 46 C21 46 15 51 4 51 C37 67 57 37 54 21 Z"/>
              </svg>
            </div>
            <div>
              <svg id="i-twitter" viewBox="0 0 64 64" width="8rem" height="8rem">
              <path stroke-width="0" fill="currentColor" d="M60 16 L54 17 L58 12 L51 14 C42 4 28 15 32 24 C16 24 8 12 8 12 C8 12 2 21 12 28 L6 26 C6 32 10 36 17 38 L10 38 C14 46 21 46 21 46 C21 46 15 51 4 51 C37 67 57 37 54 21 Z"/>
              </svg>
            </div>
            <div>
              <svg id="i-twitter" viewBox="0 0 64 64" width="8rem" height="8rem">
              <path stroke-width="0" fill="currentColor" d="M60 16 L54 17 L58 12 L51 14 C42 4 28 15 32 24 C16 24 8 12 8 12 C8 12 2 21 12 28 L6 26 C6 32 10 36 17 38 L10 38 C14 46 21 46 21 46 C21 46 15 51 4 51 C37 67 57 37 54 21 Z"/>
              </svg>
            </div>
            <div>
              <svg id="i-twitter" viewBox="0 0 64 64" width="8rem" height="8rem">
              <path stroke-width="0" fill="currentColor" d="M60 16 L54 17 L58 12 L51 14 C42 4 28 15 32 24 C16 24 8 12 8 12 C8 12 2 21 12 28 L6 26 C6 32 10 36 17 38 L10 38 C14 46 21 46 21 46 C21 46 15 51 4 51 C37 67 57 37 54 21 Z"/>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page -->
	<!--login modal -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
	<div class="sq-modal" id="myModal" >
	    <div class="sq-modal-body" style="width:24rem;">
			<header>
	            <div class="sq-close-button" onclick="toggleModal('myModal')">&times;</div>
	        </header>
	        <div class="sq-modal-content">
					<section>
						<form class="sq-form" action="index.html" method="post">
	        				<fieldset>
	          					<legend>Login</legend>
	          					<label>Email</label>
	          					<input type="email" name="" value="" placeholder="E-mail">
	          					<label>Password</label>
	          					<input type="password" name="" value="" placeholder="Password">
	          					<div class=" sq-container">
									<a href="/">
										<div class="sq-justify-left">
												<button type="button" name="">Login</button>
										</div>
									</a>
	          					</div>
	        				</fieldset>
						</form>
	                </section>
	        </div>
	    </div>
	</div>
<!--Login modal end -->
</body>
</html>
<script>
function toggleModal2(socialMedia) {
var social = document.getElementById("socialMedia");
social
    .classList
    .toggle("sq-show-modal");
}
window.toggleModal = (id)=> {
var modal = document.getElementById(id);
modal.classList.toggle('sq-modal-show');
};
</script>