lib/squareshop_web/router.ex
defmodule SquareshopWeb.Router do
  use SquareshopWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

	scope "/", SquareshopWeb do
		pipe_through :browser # Use the default browser stack
		get "/", PageController, :index
		get "/login", LoginController, :index
		get "/tos", TosController, :index
		get "/about", AboutController, :index
		get "/invoice", InvoiceController, :index
		resources "/shopping", ShoppingController
		resources "/products", ProductsController
		resources "/adminproducts", AdminProductsController
		resources "/adminuser", AdminUserController
    resources "/user", UserController
    get "/form", FormController, :index

    get "/sign-in", LoginController, :new
    post "/sign-in", LoginController, :create
    delete "/sign-out", LoginController, :delete
	end


  # Other scopes may use custom stacks.
  # scope "/api", SquareshopWeb do
  #   pipe_through :api
  # end
end

lib/squareshop/application.ex
defmodule Squareshop.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Squareshop.Repo, []),
      # Start the endpoint when the application starts
      supervisor(SquareshopWeb.Endpoint, []),
      # Start your own worker by calling: Squareshop.Worker.start_link(arg1, arg2, arg3)
      # worker(Squareshop.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Squareshop.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    SquareshopWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/squareshop/product/product.ex
defmodule Squareshop.Products do

	# Imports
	use Ecto.Schema
	import Ecto.Changeset
	import Ecto.Query, only: [from: 2]

	#Alias
	alias Squareshop.Repo
	alias Squareshop.Products
	alias Squareshop.Products.Product
	require Logger


	#search function

	def search(query, search_term) do
		wildcard_search = "%#{search_term}%"
	
		from product in query,
		where: ilike(product.name, ^wildcard_search),
		or_where: ilike(product.summary, ^wildcard_search)
	end


	#Add a product
	def create_product(productdata) do
		# Logger.debug("user_address = #{inspect(user_address)}")
		%Product{}
		|> Product.changeset(productdata)
		|> Repo.insert()
	end

	# Listing all the products
	def list_products() do
		Repo.all(Product)
	end

	def list_products(params) do
		search_term = get_in(params, ["query"])
	
		Product
		|> Products.search(search_term)
		|> Repo.all()
	end

	def get_product!(id) do
		 Repo.get!(Product, id)
	end

	# Helper function
	def change_product(%Product{} = products) do
		Product.changeset(products, %{})
	end

	def update_product(%Product{} = product, attrs) do

		Logger.debug("i ran")
		product
		|> Product.changeset(attrs)
		|> Repo.update()
	end


end

lib/squareshop/product/products.ex
defmodule Squareshop.Products.Product do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query

 	alias Squareshop.Repo
	alias Squareshop.Products
	alias Squareshop.Products.Product

	require Logger

  schema "products" do
    field :alternative_products, :integer
    field :base_price, :integer
    field :image, :map
    field :stock, :integer
    field :name, :string
    field :pnr, :string
    field :summary, :string
    field :supplier, :integer

    timestamps()
  end

  
  def list_products(params) do
    search_term = get_in(params, ["query"])

    Product
    |> Product.search(search_term)
    |> Repo.all()
  end

  def changeset(products, attrs) do
	  Logger.debug("number 2 ran")
    products
    |> cast(attrs, [:name, :pnr, :summary, :base_price, :stock, :supplier, :alternative_products])
    |> validate_required([:name, :pnr, :base_price, :stock, :supplier])
  end
end

lib/squareshop/repo.ex
defmodule Squareshop.Repo do
  use Ecto.Repo, otp_app: :squareshop

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/squareshop/sale/cart.ex
defmodule Squareshop.Sales.Cart do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
	  field :product_id, :integer
	  field :amount, :integer
  end


  def changeset(item, attrs) do

	  item
	  |> cast(attrs, [:product_id, :amount])
	  |> validate_required([:product_id, :amount])

  end
end

lib/squareshop/sale/orders.ex
defmodule Squareshop.Sales.Orders do
  use Ecto.Schema
  import Ecto.Changeset


  schema "orders" do
    field :Shipping_address, :string
    field :products, :map
    field :status, :integer
    field :user, :integer

    timestamps()
  end

  @doc false
  def changeset(orders, attrs) do
    orders
    |> cast(attrs, [:user, :products, :Shipping_address, :status])
    |> validate_required([:user, :products, :Shipping_address, :status])
  end
end

lib/squareshop/sale/sales.ex
defmodule Squareshop.Sales do
	#importing functions
		require Stripe
		import Ecto.Query
	#Setting up aliases
		alias Squareshop.Repo
		alias Squareshop.Sales
		alias Squareshop.Sales.Orders
		alias Squareshop.Identity
		alias Squareshop.Products
		alias Stripe
		alias Stripe.Charge


	def stripetest do
		 # obtained with Stripe.js
		Stripe.Charge.create(%{amount: 2000, currency: "nok", source: "tok_mastercard", description: "Charge for madison.anderson@example.com"})
	end

	def create_order(user_id, card) do
		user = Identity.get_user!(user_id)

		# for product <= user.shopping_cart do
		# Products.get_product!()
		# end



		Stripe.Charge.create(card)
	end

end

lib/squareshop_web/controllers/products_controller.ex
defmodule SquareshopWeb.ProductsController do
  use SquareshopWeb, :controller
alias Squareshop.Products
alias Squareshop.Products.Product


  def index(conn, params) do
    product = Products.list_products(params)
    render conn, "index.html", product: product
    products = Products.list_products(params)
    render conn, "index.html", products: products
  end
  
  def show(conn, %{"id" => id}) do
		product = Products.get_product!(id)
	  render conn, "product.html", product: product
	end

end

lib/squareshop_web/views/Shopping_view.ex
defmodule SquareshopWeb.ShoppingView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/about_view.ex
defmodule SquareshopWeb.AboutView do
   use SquareshopWeb, :view
end

lib/squareshop_web/views/admin_products_view.ex
defmodule SquareshopWeb.AdminProductsView do
    use SquareshopWeb, :view
 end

lib/squareshop_web/views/admin_user_view.ex
defmodule SquareshopWeb.AdminUserView do
	use SquareshopWeb, :view
end

lib/squareshop_web/views/error_view.ex
defmodule SquareshopWeb.ErrorView do
  use SquareshopWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/squareshop_web/views/form_view.ex
defmodule SquareshopWeb.FormView do
    use SquareshopWeb, :view
  end

lib/squareshop_web/views/homepage_view.ex
defmodule SquareshopWeb.HomepageView do
   use SquareshopWeb, :view
end

lib/squareshop_web/views/invoice_view.ex
defmodule SquareshopWeb.InvoiceView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/layout_view.ex
defmodule SquareshopWeb.LayoutView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/login_view.ex
defmodule SquareshopWeb.LoginView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/page_view.ex
defmodule SquareshopWeb.PageView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/products_view.ex
defmodule SquareshopWeb.ProductsView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/reg_user_view.ex
defmodule SquareshopWeb.RegUserView do
    use SquareshopWeb, :view
  end

lib/squareshop_web/views/register_view.ex
defmodule SquareshopWeb.Shared.RegisterView do
    use SquareshopWeb, :view
  end

lib/squareshop_web/views/tos_view.ex
defmodule SquareshopWeb.TosView do
  use SquareshopWeb, :view
end

lib/squareshop_web/views/user_view.ex
defmodule SquareshopWeb.UserView do
  use SquareshopWeb, :view
end

lib/squareshop_web/templates/products/index.html.eex
<div class="sq-main-layout">
  <div class="sq-products-layout-area-header sq-panel sq-justify-center sq-mb-1" style="width:100%">
      <h2 class="sq-text-center">Products</h2>
  </div>
  <div class="sq-panel sq-products-search-layout-area-panel">
    <p class="sq-justify-center">Placeholder for sort function</p>
  </div>
  <div class="sq-products-table-layout-area-panel"style="padding:0">
    <div class="sq-air-y-1 sq-panel sq-flex-wrap sq-justify-space-around">
    <!-- Product card 1 -->
    <%= for product <- @product do %>
      <div class="sq-product-card sq-card">
        <div class="sq-card-header sq-text-center">
          <p> <%= product.name %> </p>
        </div>
        <div class="sq-card-body sq-flexbox-row sq-align-center sq-justify-center">
          <img src="/images/user.png" class="sq-product-img">
        </div>
        <div class="sq-card-footer sq-text-center">
          <p class="sq-display-inline-block">Price: <%= product.base_price %> </p>
          <%# <button class="sq-nav-btn2"><%= link "Product", to: product_path(@conn, :product) ></button> %>
          <button>Buy</button>
        </div>
      </div>
      <!-- Product card 1 end -->
      <% end %>
     
    </div>
  </div>
</div>

lib/squareshop_web/templates/products/product.html.eex
<div class="sq-main-layout">
<div class="sq-p-bildepanel sq-panel">
</div>
<div class="sq-p-logpanel sq-panel sq-flex-row">
	<div class=" sq-flex-column sq-flex " style="min-width:75%;">
			<ul>
				<li>Passer hager opp til 500 m²</li>
				<li>2 til 5 cm klippehøyde</li>
				<li>Følsomme sensorer</li>
				<li>Høy sikkerhet</li>
				<li>God batterikapasitet</li>
			</ul>
		<a href="http://www.prisjakt.no" class=" sq-margin-2">Sammenlign priser på Prisjakt.no</a>
	</div>
	<div class=" sq-flex-column sq-flex sq-p-align-end" style="min-width:25%;">
		<div class="sq-p-price-card sq-flex sq-justify-center">
			<h3>2967-,</h3>
		</div>
		<button type="button" name="button">Handlekorg</button>
		<button type="button" name="button">Kjøp Nå</button>
	</div>


</div>
<div class="sq-p-details sq-panel">
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lorem leo, laoreet at porttitor ac, blandit eget mauris. Sed varius, ligula ac viverra laoreet, augue justo auctor justo, in porta libero felis eu mauris. Nunc arcu ex, tristique vitae felis ac, tristique imperdiet metus. Nullam pharetra purus mauris. Praesent dignissim ligula purus, sit amet efficitur sem ullamcorper eu. Curabitur ut pulvinar ligula. Pellentesque accumsan orci eget metus pharetra, id tristique eros malesuada. Proin fringilla semper pulvinar. Proin bibendum commodo dolor sit amet porta.
	Proin eleifend eu lacus et pretium. Nulla ac leo tellus. Donec et lobortis magna. Maecenas lacinia placerat accumsan. Praesent commodo est in mi luctus, et gravida nunc elementum. In ut convallis elit, a elementum risus. Pellentesque eget convallis elit.
	Fusce sed erat fringilla, cursus tortor id, vehicula tortor. Donec at ante porta, pulvinar odio a, condimentum felis. Pellentesque nec augue imperdiet, sagittis est ut, lacinia eros. In molestie auctor velit, a volutpat ante egestas vitae. Etiam vitae euismod risus. Nullam eu nibh nisl. Sed sed maximus nulla. Quisque accumsan, purus sit amet tincidunt faucibus, risus turpis laoreet purus, sed viverra erat ipsum sed risus. Etiam pellentesque accumsan ipsum vel lobortis. Mauris nisi sapien, consectetur sit amet massa sollicitudin, dignissim faucibus justo. Morbi sed ullamcorper ligula. Quisque dictum ullamcorper mauris, a finibus lacus posuere non. Integer rhoncus urna a leo venenatis mollis vitae ut purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam pellentesque a diam ut volutpat. Pellentesque pulvinar porta nulla tempor ultrices.
	Duis massa mauris, vestibulum sed risus bibendum, dignissim elementum tortor. Donec at gravida massa. Etiam lacinia semper ultrices. Praesent dictum at mi ac imperdiet. Donec sit amet ex ac libero convallis auctor. Suspendisse placerat nisi a nisl condimentum aliquam. Quisque dignissim facilisis pretium. Cras vitae magna vel nibh sodales pharetra. Nulla facilisi. Quisque fermentum turpis elit, ac auctor mi tempus vel. Nulla pulvinar nulla sed turpis consequat, non luctus felis accumsan.
	Donec aliquam sed nisl ut volutpat. Ut id diam ut dui varius pellentesque. Integer id dictum neque. Duis nec lobortis elit. Aenean lectus leo, lobortis id faucibus non, euismod sit amet tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pharetra posuere mauris non porttitor. Mauris volutpat tincidunt aliquam. Vestibulum dui risus, porta in nisl et, tincidunt sagittis tortor.
	Aenean euismod tellus nibh, ac ornare ligula efficitur vel. Nunc ac turpis pharetra, consectetur ligula id, lobortis neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu arcu, suscipit quis iaculis vitae, condimentum sed ante. Nam ligula quam, porttitor eget ipsum id, blandit vulputate eros. Mauris eu eros a lacus suscipit imperdiet ac in mi. Proin commodo varius eros at dictum. Curabitur semper venenatis nisi id pharetra. Fusce at odio suscipit, congue arcu quis, consequat ligula. Cras ac mauris non dui consectetur laoreet.
	Praesent sed dictum nibh. Integer turpis mi, congue maximus turpis at, faucibus molestie tortor. Aliquam hendrerit ut massa varius dignissim. Curabitur in dapibus nisl. Nulla rhoncus purus non enim efficitur tristique. Quisque sit amet lacinia augue. Quisque tempus fringilla magna a convallis.
	Cras finibus, libero eu congue gravida, nibh urna cursus tellus, et viverra mauris dui ac leo. Morbi et odio erat. Nam sit amet venenatis mi. Vivamus nec mollis quam. Fusce mauris mi, tempor sit amet fermentum et, efficitur id tellus. Proin lobortis tortor id urna tincidunt efficitur. Praesent sodales dolor eget elit pellentesque euismod.
	Vivamus ornare gravida leo, eget blandit libero dignissim a. Morbi consequat sed orci quis fringilla. Integer faucibus ante viverra nisi bibendum convallis. Aenean cursus ex eu nunc tristique auctor. Pellentesque gravida, tellus vel cursus tempus, arcu ligula sodales metus, id eleifend turpis orci sit amet urna. Nulla id maximus libero. Quisque nec rutrum leo. Vestibulum at leo quis urna pellentesque ultricies sit amet vitae nibh. Duis ut ultrices urna, a mollis magna. Sed vitae tempus quam. Aenean consectetur ante eu tortor tristique, eget interdum felis porttitor. Fusce in venenatis lacus.
	Donec venenatis accumsan dui. Nunc dictum imperdiet posuere. Nulla sodales ante velit, id luctus lorem ornare ut. Sed fringilla, nisi eget tincidunt commodo, lacus sapien ornare turpis, ut viverra metus lacus id ligula. Vestibulum imperdiet non justo vitae sollicitudin. Fusce in justo vitae justo vulputate condimentum. Sed vitae orci dolor. Mauris aliquam hendrerit nulla, sed gravida ex condimentum eu. Donec in volutpat lacus, non hendrerit lacus. Cras ullamcorper enim diam, ut pretium nunc tempus ut. Ut nulla quam, molestie eu posuere ac, venenatis vel dui. Nam faucibus lorem odio, ut dignissim metus maximus sit amet. Ut suscipit lacinia risus, et suscipit sem mollis nec.
	Integer tincidunt libero iaculis massa scelerisque fringilla. Mauris bibendum, est in volutpat interdum, augue enim ornare massa, a fringilla magna velit a nisl. Aenean eu diam est. Maecenas sapien odio, tincidunt in sapien finibus, posuere efficitur dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce efficitur nisi rhoncus magna commodo, quis consequat dolor viverra. In maximus sapien nulla. Integer elementum neque elit, ut porttitor lectus gravida ut. Duis neque odio, tincidunt blandit metus eget, tincidunt consequat felis. Proin iaculis magna non dolor semper, nec scelerisque odio vulputate. Integer euismod aliquet dolor, a blandit erat luctus sit amet.
	Integer cursus, felis id dapibus egestas, lorem dui aliquet ligula, sit amet gravida ante tellus id libero. Proin luctus porta nisl, eget fermentum diam condimentum at. Donec et gravida turpis, ut iaculis velit. Mauris scelerisque commodo rutrum. Integer tincidunt ipsum risus, aliquet tempus sem vulputate a. Quisque sodales dolor tortor, eget dapibus eros gravida a. Aenean vitae fringilla sem. Aenean sit amet lobortis dolor. Integer non mauris mi. Fusce eleifend molestie nibh non gravida. Morbi dictum, sem vestibulum dictum consectetur, magna ante pulvinar leo, dapibus auctor odio mauris at nibh.
	Sed congue magna et sem condimentum, at egestas nisl consequat. Integer accumsan arcu vel justo congue elementum. Nulla facilisi. In in vehicula augue. Nulla ac sem pretium, convallis lorem id, varius enim. Mauris vel eros sit amet mauris pulvinar interdum at sed purus. Aliquam lobortis pellentesque nunc sed varius. Nulla ornare nulla quis nisi tempus, non imperdiet ex scelerisque.
	Cras magna purus, ornare varius sollicitudin pretium, sagittis ut ex. Fusce tristique tincidunt massa, in eleifend nunc placerat nec. Ut fermentum tincidunt tellus, at mattis massa tincidunt nec. Donec tortor tortor, commodo egestas odio at, ultrices sodales sapien. Vestibulum elementum justo eget semper ullamcorper. Vestibulum id enim purus. Pellentesque lobortis massa ex, sed dictum purus consequat non. Quisque vitae mauris magna. Aenean malesuada ante in velit pellentesque, id mollis velit blandit. Cras vehicula nec nulla ultricies facilisis. Sed mattis pellentesque venenatis. Fusce in maximus libero. Maecenas a tincidunt mi. Integer ipsum nisi, tempor eget tincidunt ut, dignissim in quam.
	Nam lectus mauris, congue et vestibulum vel, euismod pulvinar nisl. Aliquam aliquam libero a semper molestie. Sed porttitor urna id purus bibendum fringilla. Morbi vel massa risus. Aliquam et mi vitae ligula mattis molestie semper ut quam. Etiam aliquet lacus id nisi vehicula placerat. Ut quis ligula erat. Ut porttitor maximus mattis.
	Ut porta odio dapibus enim tempor, at porta enim tincidunt. Pellentesque id metus vulputate, cursus quam ac, congue diam. Phasellus ornare vitae dolor at consectetur. Morbi mattis augue in augue rhoncus lacinia. Suspendisse potenti. Nunc aliquam lorem quis ipsum finibus, eget vehicula orci tempor. Etiam non semper sapien.
	Vivamus molestie nulla non turpis hendrerit, eget fringilla dolor volutpat. Donec iaculis venenatis porta. Nam vitae elit sapien. Proin metus ipsum, cursus eget leo eget, dignissim aliquet erat. Sed at arcu dignissim, sollicitudin risus in, accumsan tortor. Nulla facilisi. Etiam vehicula turpis eu velit commodo, faucibus consequat massa malesuada. Pellentesque tristique eu purus in mattis. Duis venenatis nisl vitae iaculis ultrices. Maecenas molestie quam sit amet vulputate faucibus.
	Phasellus gravida, nisi nec bibendum eleifend, tortor lacus cursus lacus, eget suscipit lorem leo volutpat urna. Mauris imperdiet dapibus eros, vitae porttitor eros malesuada non. Vivamus interdum sem sed enim tincidunt fringilla. Donec ut convallis enim. Praesent luctus semper nibh, vehicula vehicula mauris laoreet ut. Donec vitae ex risus. Nullam egestas erat ante, sit amet porta nisi bibendum vitae. Aenean malesuada felis urna. Morbi dignissim erat eu ullamcorper placerat. Nam dignissim quam vitae felis viverra scelerisque. Nunc condimentum sed dui vitae hendrerit. Sed sagittis, neque condimentum lacinia tristique, sapien ipsum hendrerit dui, vel gravida ante magna sed ipsum.
	Cras est quam, accumsan vitae iaculis non, dictum quis ligula. Quisque pellentesque id magna et volutpat. Maecenas commodo leo congue, gravida odio nec, bibendum dolor. Phasellus velit tellus, suscipit ut blandit a, pulvinar a nisl. Integer in massa cursus dui sagittis bibendum. Nullam tempor fermentum eros, ut auctor massa gravida sit amet. Cras suscipit nibh et lectus pharetra, non efficitur ante mollis. Sed quis sapien dui. Aliquam blandit metus ut ex tincidunt efficitur. Nunc et tortor diam. Vestibulum suscipit eros ut metus feugiat ullamcorper. Vivamus ac vestibulum tortor, iaculis rutrum sem. Suspendisse potenti. Integer erat ligula, ultrices ac neque quis, viverra egestas velit. Nulla pulvinar volutpat nisl, ac tempus mi auctor vitae. In quis molestie dui.
	Pellentesque fermentum, libero et tincidunt aliquet, lacus diam iaculis leo, a tempor nunc lorem vitae urna. Proin eu ante ex. Aliquam consectetur, est quis congue viverra, erat arcu commodo lectus, id dapibus erat magna quis ex. Aliquam tincidunt, felis non feugiat dictum, nulla nisl gravida libero, eu tempus nulla neque sed nisl. Suspendisse egestas, magna sed consequat ornare, ligula leo tempor nulla, nec efficitur massa dolor vitae risus. Duis sollicitudin lectus mollis risus tincidunt, at faucibus neque tempus. Praesent varius bibendum gravida.
Genererte 20 paragrafer, 1567 ord, 10597 bytes med Lorem Ipsum
</div>
</div>